/*
 * Games WITHOUT artwork/icons (rendered as UGS-style name tiles).
 * Same entry format as games-data.js. Merged into the catalog only when
 * the "Show games without icons" setting is enabled.
 */
window.NOICON_GAMES = [
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/throw%20a%20potato%20again/index.html", "", "Throw a Potato Again"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/getaway%20shootout/index.html", "", "getaway shootout"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/leader-strike/index.html", "", "leader strike"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/badegg.io/index.html", "", "badegg.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/cactus%20mccoy/index.html", "", "cactus mccoy"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/cactus%20mccoy%202/index.html", "", "cactus mccoy 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/terretorial.io/index.html", "", "terretorial.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/just%20passing%202/index.html", "", "just passing 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/jacksmith/index.html", "", "jacksmith"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/Pre%20Civilization%20Bronze%20Age/index.html", "", "Pre Civilization Bronze Age"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/strongdog%20chat/index.html", "", "Strongdog Chat"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/shipo.io/index.html", "", "shipo.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/conq.io/index.html", "", "conq.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sheep%20party/index.html", "", "sheep party"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/friday%20night%20funkin/index.html", "", "friday night funkin"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/tanko.io/index.html", "", "tanko.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/tag/index.html", "", "tag"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/level%20devil/index.html", "", "level devil"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/checkers/index.html", "", "checkers"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gladihoppers/index.html", "", "gladihoppers"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/water%20color%20sort/index.html", "", "water color sort"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/fireboy%20and%20watergirl%206/index.html", "", "fireboy and watergirl 6"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/Fireboy%20and%20Watergirl%205/index.html", "", "Fireboy and Watergirl 5"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/Fireboy%20and%20Watergirl%204/index.html", "", "Fireboy and Watergirl 4"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/Fireboy%20and%20Watergirl%203/index.html", "", "Fireboy and Watergirl 3"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/Fireboy%20and%20Watergirl%202/index.html", "", "Fireboy and Watergirl 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/Fireboy%20and%20Watergirl%201/index.html", "", "Fireboy and Watergirl 1"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/earn%20to%20die/index.html", "", "earn to die"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/paper%20minecraft%20ender%20dragon/index.html", "", "paper minecraft ender dragon"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/grindcraft/index.html", "", "grindcraft"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/pixwars%202/index.html", "", "pixwars 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/strike%20force%20heros/index.html", "", "strike force heros"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/burger%20tycoon/index.html", "", "burger tycoon"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/miragine%20war/index.html", "", "miragine war"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/traffic%20tour/index.html", "", "traffic tour"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/superfighters/index.html", "", "superfighters"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/super%20liquid%20soccer/index.html", "", "super liquid soccer"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/spelunky/index.html", "", "spelunky"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/rabbit%20samurai%202/index.html", "", "rabbit samurai 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/rabbit%20samurai/index.html", "", "rabbit samurai"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/quake/index.html", "", "quake"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/pizza%20tower/index.html", "", "pizza tower"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/party%20project/index.html", "", "party project"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/onion%20boy/index.html", "", "onion boy"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/NG%20stars/index.html", "", "NG stars"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/n-gon/index.html", "", "n-gon"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gunnight/index.html", "", "gunnight"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/freefall%20tournament/index.html", "", "freefall tournament"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/fighter%20aircraft%20piolet/index.html", "", "fighter aircraft piolet"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/die%20in%20the%20dungeon/index.html", "", "die in the dungeon"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cannon%20basketball%204/index.html", "", "cannon basketball 4"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/burrito%20bison/index.html", "", "burrito bison"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/bumpyball.io/index.html", "", "bumpyball.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/basket%20legend%202020/index.html", "", "basket legend 2020"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/basket%20and%20ball/index.html", "", "basket and ball"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/adventure%20drivers/index.html", "", "adventure drivers"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/super%20santa%20kicker/index.html", "", "super santa kicker"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/solitaire/index.html", "", "solitaire"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/nitroclash.io/index.html", "", "nitroclash.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gravity%20soccer/index.html", "", "gravity soccer"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/going%20balls/index.html", "", "going balls"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/falling%20fox/index.html", "", "falling fox"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/draw%20the%20hill/index.html", "", "draw the hill"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/color%20switch/index.html", "", "color switch"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/brawlguys.io/index.html", "", "brawlguys.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/basketbros.io/index.html", "", "basketbros.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/ballistic/index.html", "", "ballistic"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/two-punk-racing/index.html", "", "two punk racing"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/tube-jumpers/index.html", "", "tube jumpers"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/tomb-of-the-mask/index.html", "", "tomb of the mask"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/tank-io/index.html", "", "tank.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/supra-speed-racing-turbo-drift/index.html", "", "racing turbo drift"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sports/index.html", "", "sports"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sonic-revert/index.html", "", "sonic revert"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/pixelfoosball/index.html", "", "pixel foosball"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/Penguinio/index.html", "", "Penguin.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/novabilliards/index.html", "", "nova billiards"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/madalin-cars/index.html", "", "madalin cars"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gungame-shooting-warfare-blocky-gangster/index.html", "", "blocky gangster"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/grab-party-io/index.html", "", "grab party.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/dunkers/index.html", "", "dunkers"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/drift/index.html", "", "drift"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/doomz-io/index.html", "", "doomz.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/discus/index.html", "", "disc us"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/death-run-3d/index.html", "", "death run 3d"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cube-flip/index.html", "", "cube flip"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/crazy-pixel-apocalypse-3/index.html", "", "pixel apocalypse"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cleanupio/index.html", "", "cleanup.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/call-of-ops-2/index.html", "", "call of ops 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/blocky-gun-paintball-3/index.html", "", "blocky gun paintball"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/basketball_io/index.html", "", "basketball.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/baseballfury/index.html", "", "baseball fury"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/ball-mayhem/index.html", "", "ball mayhem"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/adofai/index.html", "", "A Dance of Fire And Ice"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sleepy%20knight/index.html", "", "sleepy knight"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/greedy%20mimic/index.html", "", "greedy mimic"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sticky%20sorcerer/index.html", "", "sticky sourcerer"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/yarne/index.html", "", "yarne"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/two%20timin%20towers/index.html", "", "two timin towers"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/slimoban%202/index.html", "", "slimoban 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/slide%20fill/index.html", "", "slide fill"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sheep/index.html", "", "sheep"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/roll%20merge%203d/index.html", "", "roll merge 3d"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/ordeals%20of%20december/index.html", "", "ordeals of december"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/one%20screen%20run%202/index.html", "", "one screen run 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/indestructotank%20gb/index.html", "", "indestructotank gb"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gaia/index.html", "", "gaia"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/bokdown/index.html", "", "bokdown"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/yin%20and%20yang/index.html", "", "yin and yang"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/top%20outpost/index.html", "", "top outpost"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/spirit%20dungeons/index.html", "", "spirit dungeons"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/pixel%20tap%20dungeon/index.html", "", "pixel tap dungeon"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/out%20of%20ctrl/index.html", "", "out of ctrl"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mad%20pirate%20skeleton/index.html", "", "mad pirate skeleton"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/kity%20builder%20prototype/index.html", "", "kity builder prototype"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/jetscout%20boot%20camp/index.html", "", "jetscout boot camp"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/idle%20fill%20factory/index.html", "", "idle fill factory"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/find%20a%20way%20out/index.html", "", "find a way out"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cursed%20travels%20flame%20of%20the%20banshee/index.html", "", "cursed travels flame of the banshee"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cognite/index.html", "", "cognite"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/white%20pen%20road/index.html", "", "white pen road"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/space%20cowboy/index.html", "", "space cowboy"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/rail%20connect/index.html", "", "rail connect"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/put%20a%20ring%20on%20it/index.html", "", "put a ring on it"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mutual%20destruction/index.html", "", "mutual destruction"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mini%20bubbles/index.html", "", "mini bubbles"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/leapoid/index.html", "", "leapoid"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/keyholder/index.html", "", "keyholder"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/icy%20north/index.html", "", "icy north"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/evolutionary%20psychol/index.html", "", "evolutionary psychol"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/escape%20kid/index.html", "", "escape kid"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cursed%20travels%20the%20shattered%20labyrinth/index.html", "", "cursed travels the shattered labyrinth"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/crystal%20wizards/index.html", "", "crystal wizards"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/calturin/index.html", "", "calturin"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/binary/index.html", "", "binary"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/are%20you%20human/index.html", "", "are you human"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/anyek%20the%20keyboard%20puzzle/index.html", "", "anyek the keyboard puzzle"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/adventure%20boy%20jailbreak/index.html", "", "adventure boy jailbreak"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/the%20impossible%20quiz%202/index.html", "", "the impossible quiz 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/shaky%20structure/index.html", "", "shaky structure"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/orb%20of%20creation/index.html", "", "orb of creation"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/incub8/index.html", "", "incub8"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/tryh4rd/index.html", "", "tryh4rd"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/runick/index.html", "", "runick"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/laqueus%20escape%20chapter%205/index.html", "", "laqueus escape chapter 5"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/drag%20box/index.html", "", "drag box"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cloudhopper/index.html", "", "cloudhopper"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/yarn%20untangled/index.html", "", "yarn untangled"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/towerland/index.html", "", "towerland"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/the%20mage/index.html", "", "the mage"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/telepobox%202/index.html", "", "telepobox 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/snail%20trail/index.html", "", "snail trail"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/robox/index.html", "", "robox"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/reel%20deep/index.html", "", "reel deep"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/planet%20d4rk/index.html", "", "planet d4rk"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/moosha/index.html", "", "moosha"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/may%20i%20have%20your%20attention%2C%20please/index.html", "", "may i have your attention, please"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/laqueus%20escape%20chapter%206/index.html", "", "laqueus escape chapter 6"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/house%20pusher/index.html", "", "house pusher"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gobo%20desert%20of%20cubes/index.html", "", "gobo desert of cubes"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/forward%20winds/index.html", "", "forward winds"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/fluctuoid/index.html", "", "fluctuoid"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cursed%20travels%20a%20forgotten%20seal/index.html", "", "cursed travels a forgotten seal"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/blacken%20slash%20demo/index.html", "", "blacken slash demo"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/magirune/index.html", "", "magirune"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/logica%20emotica/index.html", "", "logica emotica"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/hall%20of%20palettes/index.html", "", "hall of palettes"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/nova%20cloudwalkers/index.html", "", "nova cloudwalkers"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/notebook%20jam/index.html", "", "notebook jam"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gods%20of%20defense/index.html", "", "gods of defense"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/slide%20box/index.html", "", "slide box"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sector%2001/index.html", "", "sector 01"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/erase%20box/index.html", "", "erase box"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sum%20lines/index.html", "", "sum lines"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/strg%20snek/index.html", "", "strg snek"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/rotate%20box/index.html", "", "rotate box"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/red%20scarf%20platformer/index.html", "", "red scarf platformer"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/peeper%20reaper/index.html", "", "peeper reaper"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/ninja%20auto%20run/index.html", "", "ninja auto run"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/murder%20is%20game%20over/index.html", "", "murder is game over"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mirror%20wizard/index.html", "", "mirror wizard"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mini%20swim/index.html", "", "mini swim"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mini%20flips/index.html", "", "mini flips"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/marcus%20osnail/index.html", "", "marcus osnail"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/knights%20blade/index.html", "", "knights blade"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/infinite%20night%20the%20cunning%20princess/index.html", "", "infinite night the cunning princess"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/in%20space/index.html", "", "in space"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/hummin%20out/index.html", "", "hummin out"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/haunted%20rooms/index.html", "", "haunted rooms"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/darkraid%20delilah/index.html", "", "darkraid delilah"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cordovan/index.html", "", "cordovan"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/contractomaton/index.html", "", "contractomaton"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/arrow%20box/index.html", "", "arrow box"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/viscous%20ventures/index.html", "", "viscous ventures"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/steel%20and%20claw/index.html", "", "steel and claw"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/slime%20knight/index.html", "", "slime knight"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/platformation/index.html", "", "platformation"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/path%20of%20arrows/index.html", "", "path of arrows"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/ninja%20kite/index.html", "", "ninja kite"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mutato%20potato/index.html", "", "mutato potato"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mini%20rocket/index.html", "", "mini rocket"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/magnet%20master%20redux/index.html", "", "magnet master redux"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/inversion/index.html", "", "inversion"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/handle/index.html", "", "handle"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/dispersal%20vectors/index.html", "", "dispersal vectors"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/cata%20catapult/index.html", "", "cata catapult"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/astro%20steve%20adventure/index.html", "", "astro steve adventure"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/elephant%20rave%202/index.html", "", "elephant rave 2"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/the%20designer/index.html", "", "the designer"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/stress%20chess/index.html", "", "stress chess"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/specters%20of%20the%20sun/index.html", "", "specters of the sun"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/space%20order%20mine/index.html", "", "space order mine"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/scraplegs/index.html", "", "scraplegs"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/last%20plant%20on%20earth/index.html", "", "last plant on earth"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/gloop/index.html", "", "gloop"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/doubleup/index.html", "", "doubleup"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/toms%20trial/index.html", "", "toms trial"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/jetpack%20kiwi/index.html", "", "jetpack kiwi"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/dungeon%20scroller/index.html", "", "dungeon scroller"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/a%20maniac/index.html", "", "a maniac"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/pixelshooter/index.html", "", "Pixel shooter"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/polytrack/index.html", "", "Poly track"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/retro%20bowl%20college/game/index.html", "", "retro bowl college"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/jptragar/web/index.html", "", "agar.io"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/giraffe/index.html", "", "giraffes volleyball"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/swf/duck%20life%20tresure%20hunt/index.html", "", "duck life tresure hunt"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/un%20evergreen/index.html", "", "un evergreen"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/super%20gauntlent/index.html", "", "super gauntlent"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/slis/index.html", "", "slis"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/mini%20magbot/index.html", "", "mini magbot"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/driftmania/index.html", "", "driftmania"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/club%20tycoon/index.html", "", "club tycoon"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/blasting%20marbles/index.html", "", "blasting marbles"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/deepest%20sword/index.html", "", "deepest sword"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/sort%20the%20court/index.html", "", "sort the court"],
    ["Strongdog XP", "https://raw.githack.com/strongdogxp/strongdog2/master/html/resent/Resent-4.0-Patch-2-English.html", "", "Resent client (mc)"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/yohoho.io/index.html", "", "yohoho.io"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/smash%20karts/index.html", "", "Smash Karts"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/pathfinder/index.html", "", "Pathfinder"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/hasty%20shaman/index.html", "", "Hasty Shaman"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/one%20trick%20mage/index.html", "", "One Trick Mage"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/arcuz/base.html", "", "Arcuz"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/age%20of%20war/base.html", "", "Age of war"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/winter%20gifts/index.html", "", "Winter Gifts"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/tough%20growth/index.html", "", "Tough Growth"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/the%20dark%20one/index.html", "", "The Dark One"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/tactical%20weapon%20pack/index.html", "", "Tactical Weapon Pack"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/soul%20mirror/index.html", "", "Soul Mirror"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/push/index.html", "", "Push"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/progress%20knight/index.html", "", "Progress Knight"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/pe%20norie/index.html", "", "Pe Norie"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/orange/index.html", "", "Orange"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/life%20in%20the%20static/index.html", "", "Life in the Static"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/laqueus%20escape%20chapter%201/index.html", "", "Laqueus Escape Chapter 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/just%20passing/index.html", "", "Just Passing"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/hexa%20knot/index.html", "", "Hexa Knot"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/goodbye%20doggy/index.html", "", "Goodbye Doggy"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/generic%20fishing%20game/index.html", "", "Generic Fishing Game"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/dubstep%20raven/index.html", "", "Dubstep Raven"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/doodle%20alive/index.html", "", "Doodle Alive"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/detective%20bass%20fish/index.html", "", "Detective Bass Fish"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/cursed%20travels%20below/index.html", "", "Cursed Travels Below"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/clickventure%20castaway/index.html", "", "Clickventure Castaway"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/choppy%20orc/index.html", "", "Choppy Orc"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/cataractae/index.html", "", "Cataractae"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/cat%20house/index.html", "", "Cat House"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/cardinal%20chains/index.html", "", "Cardinal Chains"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/bunnies%20carrot/index.html", "", "Bunnies Carrot"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/aspiring%20artist/index.html", "", "Aspiring Artist"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/arcade%20wizard/index.html", "", "Arcade Wizard"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/ant%20art%20tycoon/index.html", "", "Ant Art Tycoon"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/swords%20and%20souls/base.html", "", "Swords and Souls"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/sonny2/base.html", "", "Sonny2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/sonny/base.html", "", "Sonny"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/kingdom%20rush%20frontie/base.html", "", "Kingdom Rush Frontie"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/kingdom%20rush/base.html", "", "Kingdom Rush"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/worlds%20within%20worlds/index.html", "", "Worlds Within Worlds"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/unloop/index.html", "", "Unloop"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/tower%20of%20the%20scorche/index.html", "", "Tower of the Scorche"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/there%20is%20no%20game/index.html", "", "There is No Game"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/scalak/index.html", "", "Scalak"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/sabotage/index.html", "", "Sabotage"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/roots/index.html", "", "Roots"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/rogue%20fable/index.html", "", "Rogue Fable"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/pixoji/index.html", "", "Pixoji"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/pink/index.html", "", "Pink"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/knight%20errant/index.html", "", "Knight Errant"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/hexologic/index.html", "", "Hexologic"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/gragyriss/index.html", "", "Gragyriss"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/gem%20twins/index.html", "", "Gem Twins"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/dinogen%20arena/index.html", "", "Ginogen Arena"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/cursed%20travels%20flame/index.html", "", "Cursed Travels Flame"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/clickventure/index.html", "", "Clickventure"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/blue/index.html", "", "Blue"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/beam/index.html", "", "Beam"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/a%20grim%20love%20tale/index.html", "", "A Grim Love Tale"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/a%20grim%20chase/index.html", "", "A Grim Chase"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/tavern%20master/index.html", "", "Tavern Master"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/green/index.html", "", "Green"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/stealing%20the%20diamond/base.html", "", "Stealing the Diamond"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/infiltrating%20the%20airship/base.html", "", "Infiltrating the Airship"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/fleeing%20the%20complex/base.html", "", "Fleeing the Complex"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/escaping%20the%20prison/base.html", "", "Escaping the Prison"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/breaking%20the%20bank/base.html", "", "Breaking the Bank"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/tanuki%20sunset/index.html", "", "Tanuki Sunset"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/Soccer%20Random/index.html", "", "Soccer Random"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/ricochet%20arrow/index.html", "", "Ricochet Arrow"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/Pixel%20Battles/index.html", "", "Pixel Battles"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/oil%20race/index.html", "", "Oil Race"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/Mountain%20Biking/index.html", "", "Mountain Biking"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/monkey%20mart/index.html", "", "Monkey Mart"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/maptroid/index.html", "", "Maptroid"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/hover%20racer%20drive/index.html", "", "Hover Racer Drive"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/hole.io/index.html", "", "Hole.io"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/Basket%20Random/index.html", "", "Basket Random"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/gun%20mayhem%202/base.html", "", "Gun Mayhem 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/shortcut%20race/index.html", "", "Shortcut Race"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/alienthief/base.html", "", "Alien Theif"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/checkpoint/base.html", "", "Checkpoint"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/chimneytrouble/base.html", "", "Chimney Trouble"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/diasterwillstrike/base.html", "", "Disaster Will Strike"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/drakeandthewizards/base.html", "", "Drake and the Wizards"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/electricman2/base.html", "", "Electric Man 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/freegear/base.html", "", "Freegear"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/gooballs/base.html", "", "Gooballs"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/hoshisaga1/base.html", "", "Hoshi Saga 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/hoshisaga2/base.html", "", "Hoshi Saga 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/hoshisaga3/base.html", "", "Hoshi Saga 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/iqball/base.html", "", "IQ Ball"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/iwannawin/base.html", "", "I Wanna Win"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/jellygo/base.html", "", "Jelly Go!"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/littlewheel/base.html", "", "Little Wheel"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/miniputt3/base.html", "", "Mini Putt 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/minitrain/base.html", "", "Mini Train"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papabakeria/base.html", "", "Papas Bakeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papaburgeria/base.html", "", "Papas Burgeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papacheeseria/base.html", "", "Papas Cheeseria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papacupcakeria/base.html", "", "Papas Cupcakeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papadonuteria/base.html", "", "Papas Donuteria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papafreezeria/base.html", "", "Papas Freezeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papahotdoggeria/base.html", "", "Papas Hotdoggeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papapancakeria/base.html", "", "Papas Pancakeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papapasteria/base.html", "", "Papas Pasteria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papapizzeria/base.html", "", "Papas Pizzeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papascooperia/base.html", "", "Papas Scooperia"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papasushiria/base.html", "", "Papas Sushiria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papataco/base.html", "", "Papas Taco Mia"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/papawingeria/base.html", "", "Papas Wingeria"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/portal/base.html", "", "Portal"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/pvz2/base.html", "", "Plants Vs. Zombies 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/raftwars/base.html", "", "Raft Wars"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/scrapmeatalheros/base.html", "", "Scrap Meatal Heros"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/shapeshifter/base.html", "", "Shape Shifter"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/squarehero/base.html", "", "Square Hero"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/tarzanball/base.html", "", "Tarzan Ball"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/truckloader/base.html", "", "Truck Loader"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/workingstiffs/base.html", "", "Working Stiffs"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/eaglecraft/game/Offline_Download_Version.html", "", "Minecraft (1.5.2 Eaglercraft)"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/sm64/index.html", "", "Super Mario 64"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/rocket%20league/index.html", "", "Rocket League"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/google-snake/index.html", "", "Google Snake"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/stickman-hook/index.html", "", "Stickman Hook"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/slope2/index.html", "", "Slope 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/bitlife/index.html", "", "Bitlife"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/drift-boss/index.html", "", "Drift Boss"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/snow-rider-3d/index.html", "", "Snow Rider 3D"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/planetlife/index.html", "", "Planet Life"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/findingsanta/base.html", "", "Finding Santa"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/hauntthehouse/base.html", "", "Haunt the House"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/houseofhazards/index.html", "", "House of Hazards"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/couch2048/index.html", "", "Couch 2048"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/tabs/index.html", "", "Tabs"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/ducklife1/base.html", "", "Duck Life"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/ducklife2/base.html", "", "Duck Life 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/ducklife3/base.html", "", "Duck Life 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/factoryballs1/base.html", "", "Factory Balls 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/factoryballs2/base.html", "", "Factory Balls 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/factoryballs3/base.html", "", "Factory Balls 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/factoryballs4/base.html", "", "Factory Balls 4"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/run/base.html", "", "Run 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/run2/base.html", "", "Run 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/fancy1/base.html", "", "Fancy Pants 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/fancy3/base.html", "", "Fancy Pants 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/penguin/base.html", "", "Penguin Dinner"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/bombit/base.html", "", "Bombit 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/bombit2/base.html", "", "Bombit 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/bombit3/base.html", "", "Bombit 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/comicbook/base.html", "", "Comic Book Cody"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/hotdogbush/base.html", "", "Hot Dog Bush"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/louie1/base.html", "", "Papa Louies 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/minhero/base.html", "", "Min Hero Tower of Sages"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/pandas1/base.html", "", "3 Pandas 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/shapeswitch/base.html", "", "Shape Switcher"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/strikeforcekitty/base.html", "", "Strike Force Kitty 1"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/strikeforcekitty2/base.html", "", "Strike Force Kitty 2"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/strikeforcekitty3/base.html", "", "Strike Force Kitty 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/swf/sugar/base.html", "", "Sugar, Sugar"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/adarkroom/index.html", "", "A Dark Room"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/algaes-escapade/index.html", "", "Algaes Escapade"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/9007199254740992/index.html", "", "9007199254740992"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/bad-ice-cream-3/index.html", "", "Bad Icecream 3"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/big-tower-tiny-square/index.html", "", "Big Tower Tiny Square"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/subwaysurferssanfrancisco/index.html", "", "Subway Surfers San Fran"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/subwaysurfersbeijing/index.html", "", "Subway Surfers BeiJing"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/subwaysurfershouston/index.html", "", "Subway Surfers Houston"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/subwaysurfersmonaco/index.html", "", "Subway Surfers Monaco"],
    ["Strongdog XP", "https://raw.githack.com/IAmNotTechnoblade/strongdogxp/master/html/tic-tac-toe/index.html", "", "Tic-Tac-Toe"],
];
